mod8Data <- read.table("Assignment 6 Dataset-1.txt", header = TRUE, sep = ",")
str(mod8Data)
head(mod8Data)
install.packages("plyr")
library(plyr)
install.packages("dplyr")
library(dplyr)
install.packages("stringr")
library(stringr)
studentAverage <- ddply(mod8Data, "Sex", summarise, Average = mean(Grade))
studentAverage
mod8Data %>% group_by(Sex) %>% summarise(Count = n())
df <- mod8Data %>% filter(str_detect(Name, "i"))
str(df)
head(df)
write.csv(df, "iStudents.csv")
